fix shared libs, no CALLABLE_WGRIB2, wgrib2 utility calls wgrib2(..) 234, 213, 212
NOAA-EMC/wgrib2 pull request #248
Opened 2024-09-16 15:47 UTC by webisu

wgrib2 utility calls wgrib2(..)  .. so no need for compiling wgrib2.c
with/without CALLABLE_WGRIB2 which was needed for utility vs lib build

BUILD_SHARED_LIB now works but not for python,  
  Python required external libraries to be added to libwgrib2.so.  Only way to do
  that was to build libwgrib2.a and combine with other *.a libraries
BUILD_LIB now makes relocatable code for python support.
The ftn_api library was renamed from libwgrib2_api to libwgrib2_ftn_api
Since the build for fortran codes that call libwgrib2 will be changing, it seemed
the right time to change the name of the library to something more descriptive.

In the future, the build of wgrib2_lib and obj_lib can be combined to reduce build time.

2024-10-04 15:19 UTC, AlysonStahl-NOAA requested changes

2024-10-04 15:19 UTC, AlysonStahl-NOAA commented on wgrib2/CMakeLists.txt
> +#  target_link_libraries(obj_lib PUBLIC OpenMP::OpenMP_C)
The checks are failing because of undefined references to OpenMP. Did you mean to comment this out?

2024-10-04 15:22 UTC, edwardhartnett commented on wgrib2/CMakeLists.txt
> +#  target_link_libraries(obj_lib PUBLIC OpenMP::OpenMP_C)
example:

cmake -DCMAKE_PREFIX_PATH="/home/ed/local/netcdf-c-4.9.2;/some/other/place" ..

2024-10-18 17:18 UTC, AlysonStahl-NOAA approved these changes

2024-10-18 17:26 UTC, merged